#!/bin/sh
fd="/sys/class/backlight/amdgpu_bl0/brightness"
now=$(cat $fd)
offset=2

case "$1" in
  i* ) echo "$((now+offset))" | sudo tee $fd > /dev/null 2>&1 ;;
  d* ) echo "$((now-offset))" | sudo tee $fd > /dev/null 2>&1 ;;
  *  ) echo "Usage: $(basename "$0") [ increase | decrease ]" ;;
esac
