#!/bin/sh
battery() {
  capacity=$(cat /sys/class/power_supply/BAT0/capacity)
  [ "$(cat /sys/class/power_supply/AC/online)" -eq 0 ] && echo "[$capacity%] "
}
datetime() {
  date "+[%-m/%-d %-I:%M] "
}

while true; do
  xsetroot -name " $(battery)$(datetime)"; sleep 30s
done
