#!/bin/sh
clock=$(lscpu | grep 'CPU min MHz:' | grep -o '[0-9\.]*')
mem=$(free --mebi | grep "Mem:" | tr --squeeze ' ' | cut --delimiter=' ' --field=2)
sh=$(echo "$SHELL" | sed 's/.*\/\(.*\)/\1/')
pkgs=$(pacman --query | wc -l)

echo "cpu  ${clock}MHz * $(nproc)"
echo "mem  ${mem}MB"
if [ -n "$WM" ]; then
  echo "wm   $WM"
fi
echo "sh   $sh"
echo "term $TERM"
echo "pkgs ${pkgs}"
echo
palette.py
