#!/usr/bin/env python3
def putBlock(color):
    print(f'\x1B[{str(color)}m  \x1B[0m', end='')


def putLine(begin):
    for color in range(begin, begin + 8):
        putBlock(color)
    print()


def main():
    putLine(40)
    putLine(100)


if __name__ == '__main__':
    main()
