#!/bin/sh
readonly previous_pid_fd="$XDG_RUNTIME_DIR/dwm-bar-pid"

volume() {
  pulseaudio_sink="$(pulsemixer --list-sinks \
    | grep -E "Sink:.+Default" \
    | sed -E "s/.+ID: (.+), Name:.+/\1/g")"
  if [ "$(pulsemixer --id "$pulseaudio_sink" --get-mute)" -eq 1 ]; then
    echo "muted"
    return
  fi

  echo "$(pulsemixer --id "$pulseaudio_sink" --get-volume \
    | cut -d' ' -f2)%"
}

datetime() {
  date "+%m-%d %H:%M"
}

build_status_string() {
  status_buffer="$status_buffer $(volume)"
  status_buffer="$status_buffer $(datetime)"

  echo "$status_buffer"
}

run() {
  [ -f "$previous_pid_fd" ] && kill "$(cat "$previous_pid_fd")" 2>/dev/null
  echo "$$" > "$previous_pid_fd"

  while true; do
    xsetroot -name "$(build_status_string)"

    sleep 1s
  done
}

usage() {
  echo "Usage: dwm-bar run"
  echo "               stdout"
}

case "$1" in
  s* ) build_status_string ;;
  r* ) run ;;
  *  ) usage ;;
esac
