#!/bin/sh
trackpoint_id=$(xinput list \
  | grep -i "trackpoint" \
  | sed -E "s/.*id=([0-9]+).*/\1/")
sensitivity_id=$(xinput list-props "$trackpoint_id" \
  | grep -i "coordinate" \
  | sed -E "s/.*\(([0-9]+)\).*/\1/")

xinput set-prop \
  "$trackpoint_id" \
  "$sensitivity_id" \
  "$1" 0 0 0 "$1" 0 0 0 1
