#!/bin/sh
trackpoint_id=$(xinput list \
  | grep 'TrackPoint' \
  | sed 's/^.*id=\([0-9]\+\).*$/\1/g')
sensitivity_id=$(xinput list-props "$trackpoint_id" \
  | grep 'Coordinate' \
  | sed 's/^.*(\([0-9]\+\)).*$/\1/g')

xinput set-prop \
  "$trackpoint_id" \
  "$sensitivity_id" \
  "$1" 0 0 0 "$1" 0 0 0 1
