#!/bin/sh
displays=$(xrandr \
  | grep "connected" \
  | cut --delimiter=" " --fields="1-1")
edp=$(echo "$displays" \
  | grep "eDP")
hdmi=$(echo "$displays" \
  | grep "HDMI")

if [ -z $1 ]; then
  echo "usage: xrandr-wrapper mirror"
  echo "                      docking"
  echo "                      dual"
elif [ "$1" == "mirror" ]; then
  xrandr \
    --output $edp  --mode 1920x1080 \
    --output $hdmi --same-as $edp
elif [ "$1" == "docking" ]; then
  xrandr \
    --output $edp  --off \
    --output $hdmi --mode 1920x1080
elif [ "$1" == "dual" ]; then
  xrandr \
    --output $edp  --auto --pos 0x840 \
    --output $hdmi --auto --pos 1920x0 --rotate right
fi
